### ISSUE TITLE
Txn version not supported

### ISSUE THREAD

**Issue by PizBernina** [Zondax/ledger-polkadot#100]
Since the runtime upgrade of Polkadot and Kusama (v9.10) the ledger <> polkadotjs integration has problems. Transactions (all types) fail with the error  `Txn version not supported`. Similar to what it states [here](https://support.polkadot.network/support/solutions/articles/65000176738-ledger-error-txn-version-not-supported).

This issue has also been mentioned within the Polkadot discord #general-chat by multiple community members.

Same issue as the ledger-kusama one: https://github.com/Zondax/ledger-kusama/issues/104

Thanks for looking into it

**Comment by jleni** [comment]
Related to https://github.com/LedgerHQ/app-polkadot/pull/10/files

**Comment by pale-face** [comment]
Im having this same error. Im running v7.30.0, which looks like the newest according to ledger live. Is there a newer one I should be upgrading to and if so how do i access it?

**Comment by jleni** [comment]
Could you open another issue for this?
It looks like you are using a testing environment and the version is also higher than what it is used in production.

I would prefer to keep this issue separated from the others that are production related.
