### ISSUE TITLE
Message signing on Ledger

### ISSUE THREAD

**Issue by convexman** [Zondax/ledger-polkadot#109]
Related to this issue: https://github.com/polkadot-js/extension/issues/897

Some dApps (faced this issue in https://stakefi.ankr.com/) require user to sign other payloads than transactions using their private key (basically as proof that user holds private key from certain address).

In polkadot.js extension this functionality is implemented by showing user a signing prompt with message being signed.
To prevent malicious dApps from signing transactions on behalf of user special prefix and suffix is injected into payload (it's just `<Bytes>` and `</Bytes>` ASCII encoded actually, such payload can't be valid polkadot transaction)

I wonder if this feature can be supported on Ledger?

**Comment by thomas779** [comment]
https://github.com/polkadot-js/extension/issues/897#issuecomment-989853025

**Comment by ftheirs** [comment]
Thanks for the suggestion, at the moment we are not considering this new feature, but we may consider it in the near future!

**Comment by europound** [comment]
cannot sign messages on polkdot, please fix asap

**Comment by jleni** [comment]
@europound could you please open a different issue and include more information about your problem?

**Comment by europound** [comment]
raw signing is not supported by ledger, polkadot
