### ISSUE TITLE
Txn version not supported

### ISSUE THREAD

**Issue by TheGoldenEye** [Zondax/ledger-polkadot#110]
Tried "staking.bondExtra(maxAdditional)"
got "Txn version not supported" error

polkadot app: 8.9100.0
runtime 9140

I assume the recent runtime upgrade is the cause

**Comment by cryptopiloot** [comment]
Just trying to make an ordinary transfer from ledger stash account to dot controller account.

txn not supported error

Is this because of a runtime upgrade?
Does someone know how long it will take before I can move my funds around again?

ledger live 2.36.2
Dot app 8.9100.0
Nano X

**Comment by houshengbo** [comment]
Thank you for opening this issue. I ran into exactly the same issue.

**Comment by cryptopiloot** [comment]
![96A54291-9D47-4461-A7C2-486F284B497D](https://user-images.githubusercontent.com/96067270/145988699-01392c09-2d3a-46eb-be35-799ecac3a3fd.jpeg)
![8685D6FC-C11D-4F94-864F-0780C65AAEA8](https://user-images.githubusercontent.com/96067270/145988707-e57c68b1-f918-44f3-abcf-8380cfeed3aa.png)


Just got response from ledger.

Also cannot transfer with the polkadot wallet. Only just see my funds.

I guess we have to wait it out until they fixed the issue with de dot ledger application.

**Comment by houshengbo** [comment]
Many thanks to @cryptopiloot for the updates.
You are correct. Currently we are only able to VIEW, unable to transfer at all, no matter it is with Ledger live, Polkadot.js, etc.

**Comment by nud3l** [comment]
I'm facing the same issue. As far as I can see the Polkadot Ledger app is still assuming Polkadot v0.9.10 whereas Polkadot is already on v0.9.13. I'm assuming the delay is caused by the metadata v14 upgrade, but it would be great to get a timeline for when this will be resolved also in face of the currently ongoing parachain auctions.

**Comment by houshengbo** [comment]
The issue has been resolved, after upgrading the polkadot app in Ledger to 9.9140.0
<img width="954" alt="Screen Shot 2021-12-17 at 2 33 05 PM" src="https://user-images.githubusercontent.com/1542989/146598326-57f3b915-e9b7-40d9-a687-8e53b5c5d6d7.png">
.

**Comment by dartollen** [comment]
> To folks running into this issue,
> 
> The issue has been resolved, after upgrading the polkadot app in Ledger to 9.9140.0.
> 
> <img alt="Screen Shot 2021-12-17 at 2 33 05 PM" width="954" src="https://user-images.githubusercontent.com/1542989/146598326-57f3b915-e9b7-40d9-a687-8e53b5c5d6d7.png">
> 
> .

How are you getting that version of the Polkadot app? When I install it on my Ledger, the version says 8.9100.00. Uninstalling it and reinstalling it makes no difference.

**Comment by dartollen** [comment]
Nevermind, firmware was showing as up to date but was not up to date. Upon reinstalling Ledger Live and rebooting computer, it showed firmware was outdated. Firmware update made new app version appear.
