### ISSUE TITLE
Staking transaction with proxy

### ISSUE THREAD

**Issue by PizBernina** [Zondax/ledger-polkadot#114]
This is either an issue or such transactions are not supported:

I am trying to do staking transactions with a proxy and getting the error `transaction not supported`.

Looking at the read-me it seems to be supported? Using XL and the latest versions.

![image](https://user-images.githubusercontent.com/47326745/146353775-8fff3989-7d08-48b0-bc12-0c3d829f9dc7.png)
https://github.com/Zondax/ledger-polkadot

**Comment by PizBernina** [comment]
@jleni  any idea? :)

**Comment by liapit** [comment]
Hi all!

Can I please ask you to check why I cannot sign any transaction which a proxy (on ledger) anymore?

Approximately 1 month ago I could sign transfers of funds perfectly without any issue.

We need this function urgently, can you please check as quick as possible?

@ftheirs 
@carlosala 
@jleni 

Thank you so much!
Best

**Comment by jleni** [comment]
Could you provide more information?

- What app version are you using?
- What device are you using?
- Are we talking about polkadot?
- What are you using proxy with?
- What error message do you get?

**Comment by liapit** [comment]
@jleni Thank you so much for your help! So i have an address A which is stored on a hardware device (parity signer, phone). I want to transfer funds to address B which is on another hardware device (ledger S). Address C is assigned to address A as a proxy with the right „any“ (address C is on a ledger S). The transaction from A to B which I want to do on Polkadot.js is supposed to be signed with the proxy C. Before it comes to the step which i need to sign, it fails with the error: unexpected call index. I use I am using  polkadot.js.org in Chrome and the ledger function is activated. I tried it with and without the expert mode on the ledger. We are talking about KSM and DOT. 

This is the error message: Unexpected Call Index
![image](https://user-images.githubusercontent.com/89655104/167818090-a0f9f522-4da6-42c9-80d6-ce4293841c52.png)

**Comment by liapit** [comment]
Any update please? 
@ftheirs
@carlosala
@jleni

Thank you

**Comment by ftheirs** [comment]
Hey @liapit! The error that you get is because you are calling a method that is not supported. It doesn't refer to proxy.proxy but the call that is used there.
Could you tell me or upload a screenshot with the parameters that you are using?

**Comment by ftheirs** [comment]
Hi @liapit! It was really useful, thank you a lot! I added a Zemu test, so now it's working.
There is a new release that you can try. The official release from Ledger will take some days but you could install it in NanoS and NanoS+ using installer scripts from release!
https://github.com/Zondax/ledger-polkadot/releases/tag/v12.9200.1

**Comment by liapit** [comment]
This is amazing, I thank you so much for your help! I appreciate it very much :) @ftheirs
