### ISSUE TITLE
Txn version not supported error

### ISSUE THREAD

**Issue by RononDex** [Zondax/ledger-polkadot#129]
Ever since I upgraded the firmware on my ledger nano (which triggered a wipe somehow, had to restore the ledger account from the recovery phrase) I can no longer manage my Polkadot.

Whenever I try to bond or do anything basically I get the error message "Txn version not supported"

**Comment by ftheirs** [comment]
Hi @RononDex! Could you give us more details? Which firmware version are you using?

**Comment by RononDex** [comment]
Firmware version is `2.0.2` and ledger live app is version `2.39.2`

**Comment by RononDex** [comment]
When I am trying to clear nominations, I get the following error message:

![image](https://user-images.githubusercontent.com/2249071/160432633-5a0b3492-c2be-4ac6-a0b1-7dc22dcf1e1c.png)

**Comment by RononDex** [comment]
Just tried resetting the ledger live app and readding my accounts, still the same result

**Comment by RononDex** [comment]
Ah nevermind I am dumb, I had to update the polkadot app on the ledger, now it is working :D
