### ISSUE TITLE
Is the Democracy > vote extrinsic deprecated?

### ISSUE THREAD

**Issue by anaelleltd** [Zondax/ledger-polkadot#134]
Hello,

I have been able to use Ledger + Polkadotjs Apps to vote on democracy proposals in the past using Polkadot XL.
![DotLedgervote](https://user-images.githubusercontent.com/44770354/165014292-f2b4f65a-f95b-4fd5-8918-49486a9c9f5d.JPG)

However, upon consulting the table of supported extrinsics, I notice that *vote* is no longer supported...
![DotLedgervote1](https://user-images.githubusercontent.com/44770354/165014306-d6a6b0b4-5ec9-4442-b919-847bffccbb46.JPG)

...meanwhile *remove vote* and *unlock* are still supported.
![DotLedgervote2](https://user-images.githubusercontent.com/44770354/165014319-35b691b4-1727-415f-bf9f-aa0cb84e39bc.JPG)

Is this a typo or has this functionality been removed from Polkadot XL?
Please clarify/correct the information.

Thanks.

**Comment by carlosala** [comment]
This is currently not implemeted. Probably the type changed or whatever and we have not implemented the new changes.
I think it's kinda important, so I'll check it and try to implement it for the next version.
Thanks for your report!
