### ISSUE TITLE
Support parachains -- accounts inaccessible

### ISSUE THREAD

**Issue by wickles** [Zondax/ledger-polkadot#142]
Parachains that have migrated from a separate substrate chain with their own Ledger app (e.g. Centrifuge) have left Ledger users completely unable to access their accounts without compromising the recovery seed phrase. 

https://github.com/Zondax/ledger-centrifuge/issues/35

https://www.reddit.com/r/ledgerwallet/comments/sudzz1/ledger_support_for_polkadot_parachains/

:link: [zboto Link](https://app.clickup.com/t/2jtt5a3)

**Comment by carlosala** [comment]
Hi @wickles!
Yes, we are aware of that changes that many chains are doing. In the case of Centrifuge, we have in the pipeline to create a light version of the app (just supporting balances pallet) to allow people to transact the tokens in the new chain.
Also (for example) we released a new version of [Nodle app](https://github.com/Zondax/ledger-nodle) in their new chain integrated properly as a parachain.
Thanks for the comment! 😉

**Comment by wickles** [comment]
Hi. Are there any updates on this? It has been some weeks. Thanks.

**Comment by carlosala** [comment]
There a version released in our repo for new Centrifuge chain!

**Comment by wickles** [comment]
Which one? Is it compatible with Nano X? AFAIK we can't sideload apps on the X and I'm not seeing any updates available on Ledger Live.

**Comment by wickles** [comment]
I have the updated Polkadot app now and it does not do anything to resolve the issue. I think there is some misunderstanding happening about what accounts are where and which app has access to what. Would appreciate if you could reopen this while this is still getting sorted out.
