### ISSUE TITLE
make fails: ICONNAME is not set

### ISSUE THREAD

**Issue by ndcroos** [Zondax/ledger-polkadot#149]
When I try to run 'make', I get the following error:
```
~/ledger-polkadot$ make
make -C app
make[1]: Entering directory '/home/nick-test/ledger-polkadot/app'
************ TARGET_NAME  = []
COIN  = [DOT]
TARGET_NAME  = []
ICONNAME  = []
Makefile:129: *** ICONNAME is not set.  Stop.
make[1]: Leaving directory '/home/nick-test/ledger-polkadot/app'
make: *** [Makefile:33: default] Error 2
```

:link: [zboto Link](https://app.clickup.com/t/2nna146)
Is this the right way to build the app? Do I need to build with Docker?

**Comment by ftheirs** [comment]
@ndcroos Could you build the app? For quick tests, you can use the installer scripts from release section: https://github.com/Zondax/ledger-polkadot/releases

**Comment by ndcroos** [comment]
Yes, I can build it now. Thanks.
