### ISSUE TITLE
Cross-chain depositing not works

### ISSUE THREAD

**Issue by dm3ch** [Zondax/ledger-polkadot#157]
I'm using v14.9290.0 XL version of app on my ledger.

When I'm trying to deposit DOT->xcDOT on both https://apps.moonbeam.network/moonbeam or https://polkadot.lido.fi/transfers I'm getting "Method is not supported" from Polkadot.js

Maybe it worth it to add support of that method to the app

:link: [zboto Link](https://app.clickup.com/t/2zx2d1f)

**Comment by carlosala** [comment]
I'd say that's the `XcmPallet`, could you provide the exact method used there?
We are still thinking about that, Xcm types are huge and the app might not fit in nano S (both storage and RAM).
We'll consider the suggestion, thanks!

**Comment by dm3ch** [comment]
Please provide me instructions how to get info about the used method.

P.S. I'm using Nano X

**Comment by ftheirs** [comment]
Hi @dm3ch! I reproduce the issue that you mention but I couldn't find the specific method that is used. Probably, it's one of the [XCM pallet](https://github.com/Zondax/ledger-polkadot#xcmpallet) and you can see that they are not supported yet.

**Comment by tomasmcm** [comment]
Had the same issue (it's happening in these dot liquid staking dapps: https://polkadot.lido.fi/transfers , https://bifrost.app/vstaking/vDOT , https://app.parallel.fi/cross-chain , https://apps.acala.network/bridge )
I'm using a Ledger Nano S Plus.

The methods used are `xcmPallet.reserveTransferAssets` and `xcmPallet.limitedReserveTransferAssets`. Would it be possible to add these?

**Comment by eladiogalvez** [comment]
I have the same issue here.

**Comment by carlosala** [comment]
Hi! We released a new version of the app `v16.9310.0` that also bundles those methods from `XcmPallet`.
Due to hardware limitations in the Ledger Nano S, it's only going to be available for Nano S+ and Nano X.
Thanks for the report to everyone!

**Comment by ulm0** [comment]
it worked, tysm @carlosala
