### ISSUE TITLE
'Value out of range' with democracy.vote

### ISSUE THREAD

**Issue by ansermino** [Zondax/ledger-polkadot#159]
Currently using a Ledger Nano S with firmware 2.1.0 and Polkadot XL 14.9290.0. 

When submitting a vote via `democracy.vote`. I get the error "Value out of range". Same error through https://polkadot.subsquare.io/ and polkadot.js.org/apps.

:link: [zboto Link](https://app.clickup.com/t/340mhec)

**Comment by carlosala** [comment]
I can reproduce, and I localized the bug. It'll be fixed for the next version, thanks!

**Comment by ansermino** [comment]
Thanks. Any ETA on that?

**Comment by carlosala** [comment]
You have a new version fixing it 😊 
Thanks for your report! 😉
