### ISSUE TITLE
Problem with signing utility.batch()

### ISSUE THREAD

**Issue by stepanLav** [Zondax/ledger-polkadot#165]
## Summary

In [NovaWallet](https://novawallet.io/) we encountered a problem when trying to sign `utility.batch()` and `utility.batchAll()` which contains nested calls, [example of transaction](https://polkadot.subscan.io/extrinsic/1343828-3). When we try to sign such  transaction with Ledger Nano X, an error occurs.

## Steps to reproduce
1. Build utility.batch() transaction with few nested calls, [example](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/extrinsics/decode/0x1a0008070000eaa4f8a3b4e16e3ea6718b4263378749913a2d607e9475953ab8d906bf9f74120700e87648170007050400eaa4f8a3b4e16e3ea6718b4263378749913a2d607e9475953ab8d906bf9f7412)
2. Send that transaction to Ledger Nano X for sign

### Actual result:
The Ledger return code - **`0x6D00`**

<img width="400" alt="Screenshot 2022-12-09 at 10 09 41" src="https://user-images.githubusercontent.com/40560660/206645474-202d52fc-dc43-4d3a-b65b-be6ab41026ca.png">

## Environment
Ledger Nano X
App version: Polkadot 16.9310.0

:link: [zboto Link](https://app.clickup.com/t/39qqzj2)

**Comment by carlosala** [comment]
That is not reproducible to me. I was able to sign that same transaction in my Ledger device (using polkadot.js) without problem. That error you get, INS not supported, is not related to which transaction you are trying to sign, it's related to APDU protocol. Please, check that you are building the APDU message properly.

**Comment by stepanLav** [comment]
Unfortunately for me, this is also reproduced in polkadot.js:
[Example.](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.public.curie.radiumblock.co%2Fws#/extrinsics/decode/0x1a020807000000cb68a2c03e666f346a277036e8f27c912baee3c7b41c5c19123840f3a8e8fc070010a5d4e8000705040000cb68a2c03e666f346a277036e8f27c912baee3c7b41c5c19123840f3a8e8fc)
<img width="600" alt="Screenshot 2022-12-15 at 11 29 11" src="https://user-images.githubusercontent.com/40560660/207810655-f72a6c05-ed1e-403f-92e5-a5232dcb601c.png">

All my data in ledger are updated.
<img width="738" alt="Screenshot 2022-12-15 at 11 31 50" src="https://user-images.githubusercontent.com/40560660/207810888-f6f4c070-57e6-4757-8d5c-ae5389d85782.png">


It's strange, because the same operation does work on the Kusama network, but does not on the Polkadot.

**Comment by carlosala** [comment]
Check on the readme if all calls you are trying to use are nesting supported 👌🏻

**Comment by stepanLav** [comment]
> Check on the readme if all calls you are trying to use are nesting supported 👌🏻

I see, we will look forward to supporting this feature 😊

**Comment by albertov19** [comment]
Hey @carlosala  - Are there any plans to support nesting of `utility.batch` or `utility.batchAll`?

Thanks in advance

**Comment by ftheirs** [comment]
Hi @albertov19, there are some limitations on the device and we cannot enable `utility.batch` or `utility.batchAll` within a nesting call 😞
