### ISSUE TITLE
XcmPallet.teleport_assets() support request.

### ISSUE THREAD

**Issue by stepanLav** [Zondax/ledger-polkadot#166]
In the [NovaWallet](https://novawallet.io/) we have pretty easy way to send assets between different chains with `XcmPallet.teleport_assets()`. Example of such transaction - https://polkadot.subscan.io/extrinsic/13325121-3?event=13325121-40
This is what this flow looks like in our application with ledger account:

https://user-images.githubusercontent.com/40560660/207074181-f4f9cbca-0d4a-414a-94a6-ae50feb82feb.mp4

Our users would be very glad to use the ledger in such scenarios. Is there any possibility that this functionality could be supported?

:link: [zboto Link](https://app.clickup.com/t/39quah7)

**Comment by carlosala** [comment]
This has already been implemented in Kusama, it's going to be in polkadot in next version 👌🏻
