### ISSUE TITLE
Support request. Nesting for staking.chill() / .unbond() / .bond() / .nominate()

### ISSUE THREAD

**Issue by stepanLav** [Zondax/ledger-polkadot#167]
In the [NovaWallet](https://novawallet.io/) we have pretty easy flow for staking in Polkadot network, you can find how  it is easy in our [wiki pages](https://docs.novawallet.io/nova-wallet-wiki/staking/polkadot-and-kusama).
To do it through the Ledger we need support nesting calls for `staking.chill()` / `staking.unbond()` / `staking.bond()` / `staking.nominate()`

Our users would be very glad to use the ledger in such scenarios. Is there any possibility that this functionality could be supported?

:link: [zboto Link](https://app.clickup.com/t/8676xycqg)

**Comment by ainhoa-a** [comment]
Hi @stepanLav we'll look into this.

**Comment by stepanLav** [comment]
@carlosala @ainhoa-a 
I have tested it, everything works perfectly, very much appreciated, thank you!
