### ISSUE TITLE
Issue with multisig.AsMulti

### ISSUE THREAD

**Issue by ansermino** [Zondax/ledger-polkadot#174]
I am trying to use my Ledger with a multisig. When I submit a call to multisig.AsMulti to call proxy.createPure I get this error message:
```
multisig.asMulti
Call nesting not supported
```
According to the readme both of these calls are supported. 

I am using a Nano S Plus, firmware 1.1.0, Polkadot app 19.9360.2.

:link: [zboto Link](https://app.clickup.com/t/8677gc80h)

**Comment by carlosala** [comment]
The issue with that is that `proxy.createPure` is not nesting supported, so it can't be called from another method. Which is the workflow where you need that call to be nesting supported?

**Comment by ansermino** [comment]
I am attempting to deploy a multsig which controls a pure proxy so that the multsig can later be changed by transferring ownership of the proxy.

I suppose a work around would be to deploy the proxy and then transfer ownership.

Can you expand on what it means to be "nesting supported"? If we're using a multsig it would be nice to know which other calls are not supported.

**Comment by carlosala** [comment]
A call supports nesting when it can be called from a extrinsic, not being the extrinsic itself. For example, `utility.batch` extrinstic takes, as parameters, other calls to be performed. The calls inside need to support nesting. You can see in the readme which calls do support it.
If you need that proxy.createPure, there's no problem to add it 👌🏻
We have this differentiation to avoid recursively have nested calls, which may hit the limit of the device. In the case of `proxy.createPure`, there's no issue at all. It'll be supported in the next version 👌🏻

**Comment by ansermino** [comment]
I think it would definitely make sense to support as it's the recommended and most common way of deploying a multisig.

For me this issue can be considered closed. Support in future release would be awesome :)

**Comment by ansermino** [comment]
Please make sure to include `killPure` as well. This is required to unlock the locked tokens from creating a pure proxy and destroy the proxy.
