### ISSUE TITLE
"Do not use in production" Hint Still Relevant?

### ISSUE THREAD

**Issue by peetzweg** [Zondax/ledger-polkadot#179]
It's stated quite prominently in the README "Do not use in production".
https://github.com/Zondax/ledger-polkadot/blob/main/README.md?plain=1#L28

Is this still relevant, I find this a bit unsettling to read. If only the code in the `main` branch is meant, another sentence clarifying it would benefit. :)

:link: [zboto Link](https://app.clickup.com/t/85zrr8ukw)

**Comment by jleni** [comment]
The reason this message appear here is that we don't advise using this source code directly in production. The source is always in active development.

We don't advice compiling the latest commit and using this in production.

The official final binary for each release should be taken from Ledger Live.

We will update the message to clarify.
