### ISSUE TITLE
Allow dev mode

### ISSUE THREAD

**Issue by Swader** [Zondax/ledger-polkadot#18]
For testing purposes, it would be great if we could install the app with a custom prefix. This would allow for testing it with custom Substrate chains that merely differ in SS58 prefix, enabling projects like Subsocial, Phala, and others to test for Ledger compatibility as well. Likewise, it would allow developers to test with the locally running `--dev` chain, making development much easier.

**Comment by jleni** [comment]
Unfortunately, given substrate design, tx schema changes substantially. 
So normally support for new chains is not limited to a small variation in the SS58. Instead, it is necessary to update the tx parser to align with the runtime metadata. This is a not simple process.

**Comment by Swader** [comment]
Rough. What can we do to help this along on our end at W3F / Parity?

**Comment by jleni** [comment]
There is nothing specific that can be done really. 
To have an app that works for other substrate change we need to consider how these chains modify substrate, what standard pallets, new pallets, custom types, etc. they are using. Node metadata is not enough to describe a chain and each chain has written custom code and new functionality. This is the same for Ledger apps.
