### ISSUE TITLE
Enable nesting for proxy.addProxy and proxy.removeProxy

### ISSUE THREAD

**Issue by ansermino** [Zondax/ledger-polkadot#181]
Please add support for nesting of proxy.addProxy and proxy.removeProxy. These are important features for effective multisig management. 

:link: [zboto Link](https://app.clickup.com/t/8677nfb7v)

**Comment by ansermino** [comment]
Any updates on this? Can I expect this to get included? @carlosala

**Comment by carlosala** [comment]
I have it in mind, it'll be done in next version :)

**Comment by ansermino** [comment]
@carlosala Any ETA on this?

**Comment by ansermino** [comment]
@carlosala Can you confirm this was included in the latest release? There is no changelog and no commits appear relevant.

**Comment by ansermino** [comment]
We will be discontinuing the user of ledger for managing our Polkadot and parachain accounts. This functionality should be enabled without needing to request it. A 6 week turn around for what is seemingly trivial to implement is concerning and make us uncomfortable depending on the Polkadot app.

A risk of OOM failure would be very much preferred to having to request transaction constructs to be enabled.

**Comment by Xexr** [comment]
+1 for wanting this, there's a renewed focus on upgrading to multisig at present and this is a blocker currently for polkadot/ksm

Appreciate all your efforts, you're doing great work

**Comment by carlosala** [comment]
It was already implemented in spec 9420, I just didn't informed because it looked like @ansermino was not interested anymore.
@Xexr you'll be able to use it as soon as spec 9420 will be active and you app updated to latest version👍

**Comment by Xexr** [comment]
Oh excellent, how long does it typically take the latest update to makes it way to ledger live?

**Comment by carlosala** [comment]
before spec 9420 will be applied in mainnet for sure
