### ISSUE TITLE
[Request] - Add support for join in nomination pool thought Ledger Live

### ISSUE THREAD

**Issue by black00019** [Zondax/ledger-polkadot#186]
Hi,
it's possible to  add support for join in nomination pool 
through Ledger Live, without pass to Polkadot Staking Dashboard?
thanks

:link: [zboto Link](https://app.clickup.com/t/863gm89nc)

**Comment by carlosala** [comment]
We are not responsible for Ledger Live integration, Ledger handles that.
Even though, that's not likely to happen as nomination pools are quite difficult to implement, Polkadot Staking dashboard is probably your best option.
