### ISSUE TITLE
New upcoming nomination pool extrinsics that need nesting

### ISSUE THREAD

**Issue by rossbulat** [Zondax/ledger-polkadot#190]
This is an issue to flag some upcoming extrinsics (that are on Westend now) but will be on Kusama and Polkadot in the next runtime upgrade. These would need nesting enabled to work with proxy and batch calls as they are rolled out in the staking dashboard.

#### Extrinsics related to pool commission 👀

- nominationPools.claimCommission
- nominationPools.setCommission
- nominationPools.setCommissionChangeRate
- nominationPools.setCommissionMax

#### Extrinsics related to permissionless claiming of pool rewards ✓

- nominationPools.setClaimPermission
- nominationPools.claimPayoutOther

Thank you, I am happy to clarify any of these calls or provide any additional info if needed.

:link: [zboto Link](https://app.clickup.com/t/861mu9wgb)

**Comment by carlosala** [comment]
Hi Ross!
We'll keep this in mind for next release and ping you if some call might not be able to be nesting enabled! (even though, they all seem to fit at first sight!)
Thanks for the report!

**Comment by rossbulat** [comment]
Thanks @carlosala!

**Comment by carlosala** [comment]
This has been added for spec 9430 👌🏻

**Comment by rossbulat** [comment]
🎉 Excellent!
