### ISSUE TITLE
Nesting not supported error for proxy.proxy(staking.bondExtra)

### ISSUE THREAD

**Issue by rossbulat** [Zondax/ledger-polkadot#192]
I am testing `proxy.proxy` with Ledger on staking dashboard, and getting the nesting not supported error when I attempt to sign a proxied call to staking.bondExtra. The transaction is as follows:

<img width="411" alt="Screenshot 2023-06-10 at 20 55 45" src="https://github.com/Zondax/ledger-polkadot/assets/13929023/9b4eec9e-1cba-43a5-b607-587fea0f477d">

My previous tests with `balance.transfer` are working, but despite the nesting guidance on the README, bondExtra is not working with proxy.proxy. Edit. Also tried with unstake, same error.

:link: [zboto Link](https://app.clickup.com/t/86783zc29)

**Comment by carlosala** [comment]
Could I get the hex-encoded extrinsic?

**Comment by rossbulat** [comment]
Sure, this is the hex representation of the above `ExtrinsicPayload`:
```
0xb01d00001eec92559de5be4295be18caa79400d49466b8b06a4c819e766a7b79ad3b846d0007010700e40b5402f501ac009a2400001400000091b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3c8c413ae2cddbcb6c764e44b700adced48f1c1c0a03935fdf176262f7cc75fe7
```

**Comment by carlosala** [comment]
Ok, I saw now what's going on. We added that nesting on latest version, therefore it only applies to spec 9420.
It'll work when runtime upgrade hits.

**Comment by rossbulat** [comment]
Thanks for checking it out, no worries, will be sure to do more testing once 9420 is deployed.
