### ISSUE TITLE
Request: Enable nesting for convictionVoting pallet

### ISSUE THREAD

**Issue by michalisFr** [Zondax/ledger-polkadot#193]
I'm opening this issue to request that you enable nesting for the convictionVoting pallet.

With the coming of OpenGov to Polkadot and the new delegation dashboard, being able to batch calls from the `convictionVoting` pallet, especially `delegate` and `undelegate` has become very important.

:link: [zboto Link](https://app.clickup.com/t/861myvneq)

**Comment by jeluard** [comment]
`removeVote` and `unlock` would be appreciated too, as they are usually used in conjonction to the delegation related extrinsics.

**Comment by carlosala** [comment]
We'll add all the pallet, sure 👌🏻

**Comment by carlosala** [comment]
This has been added for spec 9430 👌🏻
