### ISSUE TITLE
support for setting validator session keys with a staking proxy

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-polkadot#196]
related to #184 

Previously it was possible to have a controller in a Ledger and set session keys for a validator. Now I get 'Call nesting not supported' while trying to perform this operation with a staking proxy on a ledger.

Also reported here:

https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748/27?u=nicolasochem

:link: [zboto Link](https://app.clickup.com/t/8692j9hr7)

**Comment by carlosala** [comment]
Which is the exact extrinsic you are submitting?

**Comment by nicolasochem** [comment]
It's `session:setKeys`

https://polkadot.js.org/docs/substrate/extrinsics/#setkeyskeys-kitchensinkruntimesessionkeys-proof-bytes

**Comment by carlosala** [comment]
Thanks for the report! It'll be fixed in next version 👍🏻

**Comment by nicolasochem** [comment]
it works
