### ISSUE TITLE
Nesting support for staking.payoutStakers

### ISSUE THREAD

**Issue by rossbulat** [Zondax/ledger-polkadot#199]
This is a request to add nesting support to `staking.payoutStakers`. It is likely that large nominators will receive payouts from multiple validators for an era, in which case we would like to batch these calls and get the total era payout in one submission.

Another flow is to claim all outstanding payouts from multiple eras in one transaction, in which case this will also be needed.

Note: this call will likely change in the future as https://github.com/paritytech/polkadot-sdk/pull/1189 is close to being merged - which allows payouts to be paginated and claimed on a per-page basis.

:link: [zboto Link](https://app.clickup.com/t/8692mkqh0)

**Comment by carlosala** [comment]
Sure, it'll be added in the next version 👌🏻

**Comment by rossbulat** [comment]
Awesome! Thank you @carlosala
