### ISSUE TITLE
staking.validate() fails with "nesting not supported" error when using staking proxy

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-polkadot#204]
Hi again,
Thanks for fixing #196. However I am now seeing the same problem with "validate" operation. This also was a supported controller action with Ledger!

This is the exact extrinsic: https://polkadot.js.org/docs/substrate/extrinsics/#validateprefs-palletstakingvalidatorprefs

This operation turns a stash account into a valdator. I should be able to run this operation with a staking proxy on a Ledger.

Please add support! thanks in advance.

:link: [zboto Link](https://app.clickup.com/t/869347dfw)

**Comment by carlosala** [comment]
Sure! We'll keep it in mind for next version!
