### ISSUE TITLE
Impossible to claim Manta Atlantic tokens.

### ISSUE THREAD

**Issue by newdeveloper19954** [Zondax/ledger-polkadot#208]
When you try to claim tokens on this https://app.manta.network/manta/bridge. You receive error that this transaction is not supported by Ledger.

**Comment by ftheirs** [comment]
This app only supports Polkadot chain. You won't be able to sign transactions from Manta network using this app

**Comment by adrmnv** [comment]
> This app only supports Polkadot chain. You won't be able to sign transactions from Manta network using this app

Could you please tell me if there is any way to transfer polkadot wallet from ledger to polkadotjs?
