### ISSUE TITLE
make (new) Ledger Polkadot App available for older firmware versions

### ISSUE THREAD

**Issue by web3-000** [Zondax/ledger-polkadot#209]
Please make sure that Ledger is offering the new generic Polkadot app (better also the current one) to users running other firmware than the very newest one. With the current situation you are cutting MANY ledger users that avoid firmware updates for one or the other reason (Ledger Recover e.g.) out of their funds and/or out of the Polkadot ecosystem. This is a serious adoption-killer for Polkadot. Context: inability to sign Polkadot-transactions with older versions of the Polkadot-App. With other chains its totally possible to participate in the network with older app-versions. I among others can not access my DOT on my Ledger Nano X (firmware 2.1.0) for this reason.

:link: [zboto Link](https://app.clickup.com/t/8693p077m)

**Comment by carlosala** [comment]
Hi, thanks for your report!
We don't control the firmwares Ledger chose to release the app. You could contact Ledger support for it.

**Comment by web3-000** [comment]
But you work with Ledger, so I'm sure you could try to use your influence on them regarding this.
