### ISSUE TITLE
Trying to use the same seed generated from https://polkadot.js.org/apps/#/accounts on my Ledger device.

### ISSUE THREAD

**Issue by mrkimchi** [Zondax/ledger-polkadot#21]
Hi Juan or Natanael, 

I would like to derivative on my Ledger the same public key address generated on https://polkadot.js.org/apps/#/accounts 

![Screenshot from 2020-09-22 16-43-52](https://user-images.githubusercontent.com/61117701/93898103-24a0ec80-fcf3-11ea-86df-898a4e836aa7.png)

I have imported the seed (24 words) to my ledger. Then I clicked the button "Add Ledger" at Polkadot JS APP. Do you know  which account type and address index do I need to select?

Thank you in advance.

**Comment by jleni** [comment]
Hi! This is not possible. Ledger devices use standard BIP39 and later a BIP44 derivation. This is not the case of substrate. At the moment, there is unfortunately no mnemonic portability.

**Comment by jleni** [comment]
As a reference, this is the "special" BIP39 variation that I believe polkadot.js uses: https://github.com/paritytech/substrate-bip39

**Comment by mrkimchi** [comment]
Thanks for your reply Juan.

**Comment by jleni** [comment]
as an additional reference.. this has been documented here:
https://wiki.polkadot.network/docs/en/learn-accounts#portability

**Comment by jleni** [comment]
and here
https://wiki.polkadot.network/docs/en/learn-accounts#seed-generation
