### ISSUE TITLE
Generic Polkadot App

### ISSUE THREAD

**Issue by leonardocustodio** [Zondax/ledger-polkadot#212]
Hello,

I saw an article last year that you guys were making a generic Polkadot app. From what I remember, that would require a few changes on the metadata standard or something.

Is there any place where we can see the progress of that? Or an ETA?

Regards,
Leonardo

**Comment by ftheirs** [comment]
Hi @leonardocustodio! You can check the updates from sub0 on youtube!
https://www.youtube.com/watch?v=wVMsWdwkfkA
