### ISSUE TITLE
[Question] Generate testcases

### ISSUE THREAD

**Issue by leonardocustodio** [Zondax/ledger-polkadot#217]
Hello, is there a way to generate the mock data from here? 
https://github.com/Zondax/ledger-polkadot/blob/main/tests/testcases_current.json

:link: [zboto Link](https://app.clickup.com/t/8694n7aqy)

**Comment by Admin661** [comment]
Hello @leonardocustodio yes, you'll have to use the ledger loptimal weblink.

**Comment by leonardocustodio** [comment]
@Admin661, you know that people here are very experienced developers, right?

**Comment by Admin661** [comment]
> @Admin661, you know that people here are very experienced developers, right?

Sure and I just told you what to do.
