### ISSUE TITLE
Adjust RewardDestination with entry 3 (payouts to any account)

### ISSUE THREAD

**Issue by jacogr** [Zondax/ledger-polkadot#22]
Reported here https://github.com/polkadot-js/apps/issues/3770#issuecomment-699451825

- For Kusama https://github.com/Zondax/ledger-kusama/blob/master/app/src/substrate_types.c#L295-L304
- For Polkadot https://github.com/Zondax/ledger-polkadot/blob/master/app/src/substrate_types.c#L303-L312

(It affects both apps, only logging it here since I would assume the change would be the same)

**Comment by nicolasochem** [comment]
Can this be bumped up the priority list? It has been an issue for a long time now.

**Comment by bogdan-alexandrescu** [comment]
Can we please fix this ASAP. I am stuck in a very weird spot because of this and relying on Ledger...

**Comment by nicolasochem** [comment]
If you are stuck, you can set controller to a non-ledger address using
setController() extrinsic, change the destination, then set it back to the
ledger.

**Comment by DrW3RK** [comment]
Right. @nicolasochem 's fix might work out for you. Set a controller account on Polkadot JS for your ledger account and then use it to sign the transaction for changing rewards destination address

If you are new to the controller/stash account terminology, watch this video from 6.14 - https://www.youtube.com/watch?v=FCXC0CDhyS4

**Comment by bogdan-alexandrescu** [comment]
Is there a guide on how to use setController() extrinsic? How would I do this? Can this be done via the Polkadot.js extension or webapp?

**Comment by DrW3RK** [comment]
This can be done via Polkadot JS

![image](https://user-images.githubusercontent.com/86818441/140430091-94c63828-bdbc-4f90-901e-516e969f5be9.png)

**Comment by bogdan-alexandrescu** [comment]
You are a genius! That totally fixed my issues! Many thanks!!

**Comment by zaibon** [comment]
Can we re-open this issue, cause the root cause of the bug has not been fixed yet. 
We should not have to use the workaround to be able to choose a destination account for staking reward.

**Comment by ainhoa-a** [comment]
@zaibon our latest upgrade solves this issue

**Comment by zaibon** [comment]
you mean v12.9200.0 ? Cause I did upgrade my ledger yesterday and still had the issue.
Maybe you released just after my try....

**Comment by ainhoa-a** [comment]
Hi @zaibon the PR is still open on Ledger's side https://github.com/LedgerHQ/app-polkadot/pull/22  but should be merged soon.
