### ISSUE TITLE
Kusama Coretime Parachain - Not working

### ISSUE THREAD

**Issue by lobis** [Zondax/ledger-polkadot#235]
When trying to use the ledger app in the Kusama Coretime system parachain, I am met with the error `Data is invalid : Unexpected buffer end` when trying to send funds, configure a proxy, etc. The same methods that fail in the Coretime parachain work without issue in the People chain, so I assume this is a bug. Otherwise please let me know how to proceed.

I am using subwallet.

Thanks!

:link: [zboto Link](https://app.clickup.com/t/8696q0cp3)

**Comment by Emmaward090** [comment]
> When trying to use the ledger app in the Kusama Coretime system parachain, I am met with the error `Data is invalid : Unexpected buffer end` when trying to send funds, configure a proxy, etc. The same methods that fail in the Coretime parachain work without issue in the People chain, so I assume this is a bug. Otherwise please let me know how to proceed.
> 
> I am using subwallet.
> 
> Thanks!


We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:LED09321
[Ledger support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by lobis** [comment]
> > When trying to use the ledger app in the Kusama Coretime system parachain, I am met with the error `Data is invalid : Unexpected buffer end` when trying to send funds, configure a proxy, etc. The same methods that fail in the Coretime parachain work without issue in the People chain, so I assume this is a bug. Otherwise please let me know how to proceed.
> > I am using subwallet.
> > Thanks!
> 
> We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly. Ticket ID:LED09321 [Ledger support Network](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
> 
> To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

Wow, crypto scammers on a GitHub issue, that is unexpected (not really, sadly). I remove the link from the reply.

**Comment by lobis** [comment]
This was solved. It was an issue with the SubWallet app where it didn't have the Coretime network configured by default and had to be manually configured. After doing so, transactions works as expected.
