### ISSUE TITLE
Upgraded Ledger Nano X firmware and now cant add accounts in polkadot.js.org

### ISSUE THREAD

**Issue by raoulmillais** [Zondax/ledger-polkadot#30]
I can get to the "Add account" UI on polkadot.js.org and clicking save initiates the pin request on the device. After entering the pin successfully it either gives me an indefinite spinner or says "App not open".  Looking in the chrome devtools when receiving the error case there is:

```
main.ed2ca610.js:35 Error: App does not seem to be open
    at a (polkadot.02.784ba675.js:1)
    at t.default.value (main.ed2ca610.js:1)
    at /apps/async https:/polkadot.js.org/apps/main.ed2ca610.js:1
    at async t.default.value (main.ed2ca610.js:1)
    at /apps/async https:/polkadot.js.org/apps/main.ed2ca610.js:35
```

I have the same problem on both my arch linux machine (latest stable chromium) and my Macbook Pro (Google Chrome 86.0.4240.111)

Here are the versions on my Ledger Nano X device:

Polkadot app version v5.23.0
Firmware version: Secure Element 1.2.4-5 / Microcontroller 2.10 / Bootloader 1.4 

This used to work fine before upgrading the firmware.  Upgrading the firmware triggered an app reinstall, so I can't check the polkadot ledger app version I used to have unfortunately.

**Comment by jleni** [comment]
I would suggest the following workflow (a slightly different from what you did)

1. Enter the PIN
2. Open the Polkadot App
3. Click Add account in the UI

As far as I know, when you click add account the request is immediately sent to the app. If you don't have the app already opened, then it will fail. You need to open the device before clicking "Add Account".

**Comment by raoulmillais** [comment]
Thanks @jleni that works :+1: It would be nice to have this just work (TM) regardless of the order of execution of the steps (or if that's not possible to update the message with an explanation) so as not to confuse new users like me :smile:

**Comment by jleni** [comment]
Yes, I understand. Unfortunately that would require changes in polkadot.js not the app itself.

Like polkadot.js keeps retrying until detects that you've open the app. We cannot really control this at the app level.
