### ISSUE TITLE
Left arrow in first page

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-polkadot#34]
There is a left arrow on the transaction flow (in general) even though we already are on the most left screen (the first screen appearing when starting the tx).
Let's remove it.

**Comment by emmanuelm41** [comment]
We need more data about this issue. The left arrow on the most left screen is not present in any test case.

**Comment by jleni** [comment]
This seems to be happening in Ledger Nano X. 
I can have a look at it.

**Comment by emmanuelm41** [comment]
Should this issue be closed?

**Comment by jleni** [comment]
Yes, sorry! Forgot about it
