### ISSUE TITLE
Catch when trying to access the app while the device is locked

### ISSUE THREAD

**Issue by amougel** [Zondax/ledger-polkadot#35]
It would help the UX to have something implemented like in [BTC app](https://github.com/LedgerHQ/app-bitcoin/search?q=os_global_pin_is_validated) to ensure the device is unlocked before trying to initiate a transaction.

**Comment by jleni** [comment]
waiting for info

**Comment by amougel** [comment]
Current internal investigation in progress. It seems the 5.26.1 does implement it properly and the Live needs to be corrected

**Comment by jleni** [comment]
Closing for now. Please reopen if the situation changes.

**Comment by amougel** [comment]
@jleni I made a mistake, the 5.26.1 does not implement it : it returns 0x6986. On the other hand, the code change in the merge is correct: 0x6982.
