### ISSUE TITLE
Any way to customize the derivation path format?

### ISSUE THREAD

**Issue by saltednutz825** [Zondax/ledger-polkadot#39]
Currently polkadot portal only allow derivation path in //0~19//0~19 format
But most people may come from parity signer, which use //polkadot as the default derivation path
I think it would be great if there's a way to use a user-specified derivation format
so that those who came from parity signer can use the same seed on a ledger, rather than unbonding funds and wait for a month then transfer to the new wallet.

**Comment by jleni** [comment]
migrated the issue as this is not JS related
