### ISSUE TITLE
LNS: Cannot go back previous 'APPROVE' once 'REJECT' is reached

### ISSUE THREAD

**Issue by amougel** [Zondax/ledger-polkadot#48]
On any flow on nano S, once the 'REJECT' screen is reached, you cannot go back further than 'APPROVE' even though the left arrow is displayed. If you only scroll until 'APPROVE' you are able to go back left without issue.

**Comment by jleni** [comment]
I fixed this in Kusama, we need to port and check the fix here too

**Comment by jleni** [comment]
@raynaudoe I fixed this already in Kusama (even included some zemu tests). Could you port the fix over here?
Most likely, we need to upgrade zxlib (the fix was actually there)
Let's talk in Slack if you have questions, I can explain

**Comment by raynaudoe** [comment]
Sure, I'll take a look
