### ISSUE TITLE
Improvement: Remove trailing 0

### ISSUE THREAD

**Issue by amougel** [Zondax/ledger-polkadot#49]
In some flows (at least 'Transfer keep alive' and 'Withdraw unbonded'. I'll try to review and list all flows that are impacted), the 'Value' screen displays trailing 0s after the last significative digit. It would be easier to read if we removed them

**Comment by jleni** [comment]
@raynaudoe I think this has been fixed already.. but you can probably confirm it

**Comment by raynaudoe** [comment]
yes, this is already fixed on dev branch
