### ISSUE TITLE
Upgrade to Polkadot 12

### ISSUE THREAD

**Issue by DemiMarie-parity** [Zondax/ledger-polkadot#5]
https://github.com/paritytech/polkadot/pull/1315

**Comment by jleni** [comment]
awesome! is there an expected release date?

**Comment by DemiMarie-parity** [comment]
I am not sure.

**Comment by jleni** [comment]
Updating the name to track the upgrade to Polkadot v12

**Comment by DemiMarie-parity** [comment]
Would it be possible to support both `tx_version`’s in the same app?  That would eliminate downtime.
