### ISSUE TITLE
UI displays addresses without network prefix

### ISSUE THREAD

**Issue by DemiMarie-parity** [Zondax/ledger-polkadot#6]
This could be very confusing to users, and might very well cause them to blindly accept transactions (because they can’t do anything otherwise).

**Comment by jleni** [comment]
As discuss in Riot. Should we close and/or rephrase this issue?

I don't think what you are seeing is about missing network prefixes. Instead, it is likely that you are running a devnet where the genesis hash does not match Polkadot's so the app uses then a generic prefix.

**Comment by DemiMarie-parity** [comment]
@jleni I didn’t realize that the prefix was computed from the genesis hash.  That explains why the app is always showing the genesis hash in the UI.

**Comment by jleni** [comment]
Ok, I will close this then.. but we can discuss offline how we can support Polkadot devnets.
