### ISSUE TITLE
Ledger app issue

### ISSUE THREAD

**Issue by nl9u** [Zondax/ledger-polkadot#64]
I have tried installing the polkadot app on both a Nano X and Nano S (apps successfully installed on latest firmware) using Ledger Live. However, on both devices, the app crashes a few seconds after opening it on the Ledger device.

**Comment by jleni** [comment]
HI @nl9u,

This is very interesting! 

It is the first time we hear something like this being reported and apps or Ledger firmware has not been modified for several months already with many active users.

- Could you describe what happens in those seconds between you open the app and it crashes?
- How would you describe this crash? is the app exiting?
- What application do you have open when this happens?
- Is this the only application that you have installed in these devices?

Any additional information would be very useful as this error you are describing seems a very special situation and I find it very curious and interesting.

**Comment by jleni** [comment]
We are currently investigating, it seems that Ledger themselves released a new build today that we were not aware of.
I will keep you updated

**Comment by dartollen** [comment]
Hi, I am also having the same problem, with both the Polkadot and Kusama apps on my brand new 

Ledger Nano S (running latest firmware 1.6.1). 

When I try to open either app, the app loads, but at the same time my computer plays the "USB device unplugged" sound. A couple of seconds pass, and then same sound plays again, and then the app crashes.

If I have the "sign transaction" window open on polkadot.js.org/app with a transaction ready to sign, there is sometimes just enough time to hit "sign". If I manage to do it in time, the app does not crash and proceeds to sign the transaction. Once the transaction is signed, the app stays open and thereafter behaves correctly.

I attach a video to illustrate what is happening:

https://user-images.githubusercontent.com/78418172/106595273-3620bd80-654b-11eb-8d50-63995ddb723b.mp4

Thanks for any help you can offer.

**Comment by nl9u** [comment]
The crash I have been experiencing is identical to this video

**Comment by dartollen** [comment]
Just wanted to confirm that this crash is still happening with the latest version of the Kusama/Polkadot Ledger apps (the one which includes the recovery mode to release stuck KSM/DOT). Is anyone looking into this?

**Comment by jleni** [comment]
We have definitely looked at this and worked with Ledger on this too.

At the moment, we have not detected any situation that can lead to a crash. What we have seen in the field, is that Ledger Live has a new feature that request devices to "QUIT" apps. So if you have Ledger Live open, it may happen that apps are requested remotely by Ledger Live to close.

Is it possible that this is your case? Did you have Ledger Live open while this happens?

**Comment by jleni** [comment]
Do you have any updates on this?
Is my theory about Ledger Live closing the app possible?

**Comment by dartollen** [comment]
Yes, closing Ledger Live prevents the crashing - thanks. The thing is that the Polkadot/Kusama apps are so large that you have to uninstall/reinstall them each time you want to use them, which is why I suspect people will often have Ledger Live open when running the apps.

**Comment by jleni** [comment]
We are working on a solution for Nano S. 
Polkadot/Kusama are very complex with a very large amount of operations. 
We are working on a light version with support for the most common operations only. 
It will be available soon.
