### ISSUE TITLE
wen message signing?! wen 🚀 🚀 🚀  🌙 

### ISSUE THREAD

**Issue by sleepdefic1t** [Zondax/ledger-polkadot#65]
> Specifically eyeing this:  
>* [CIP 8: Message Signing](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0008/CIP-0008.md)
>* [[Repl] Shelley Message Sign WASM Demo](https://repl.it/@sleepdefic1t/ShelleyMessageSignWASM#index.js)
>
> https://github.com/Zondax/ledger-polkadot/issues/65#issuecomment-779886131

**Comment by sleepdefic1t** [comment]
@jleni 
Any plans for message signing?

**Comment by jleni** [comment]
could you list the specific pallet/methods that you would like us to support?

**Comment by sleepdefic1t** [comment]
Specifically eyeing this:  
* [CIP 8: Message Signing](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0008/CIP-0008.md)
* [[Repl] Shelley Message Sign WASM Demo](https://repl.it/@sleepdefic1t/ShelleyMessageSignWASM#index.js)

**Comment by jleni** [comment]
It is unclear how this is relevant. Those links refer to Cardano / ADA
