### ISSUE TITLE
Ledger - Polkadot Setup Issue

### ISSUE THREAD

**Issue by NamaCitta** [Zondax/ledger-polkadot#66]
I am attempting to set up Polkadot on my new Ledger Nano X.  I have followed the step to "Add Ledger", and Add Account Via Ledger (selecting Account Type 0 twice), and I click Save but the app crashes at that point and does not add the Ledger account.  I tried this several times, and yesterday it did add the Ledger account and I was able to transfer 1 DOT to the account, but today the Ledger does not show as an account and the file is crashing when I attempt to reinstall.  I am glad I only transferred 1 DOT rather than my full DOT balance.  Any suggestions on how to remedy this problem?

The Polkadot page also displays:

One of more extensions has been detected in your browser, however no accounts has been injected.

Ensure that the extension has accounts, some accounts are visible globally and available for this chain and that you gave the application permission to access accounts from the extension to use them.

**Comment by moldovanflorin93** [comment]
@jleni can you help us please?

**Comment by StreamOfMaya** [comment]
Hi,

Thank you for reaching out to us.

This is a question best addressed to Polkadot directly. Polkadot has a compressive support page with a list of questions and answers on a variety of topics (https://support.polkadot.network/support/home).

In case you do not find a satisfactory answer, you can email their Support (support@polkadot.network) for further assistance.

We will close this issue if we do not hear back from you within 3 weeks. If you feel you have been mistakingly redirected to Polkadot, let us know.

Thanks you.
