### ISSUE TITLE
Error on connection with ledger

### ISSUE THREAD

**Issue by CryptoOsanu** [Zondax/ledger-polkadot#70]
Hello.
When I want to connect my ledger to polkadotjs, I receive an error. ( same error on chrome extension and on https://polkadot.js.org/apps/#/accounts )
My ledger is updated, and also it is on polkadot application, and the ledger live is closed.
![image](https://user-images.githubusercontent.com/7139332/109279517-81fd1480-7822-11eb-875c-64e5e1c6925a.png)
Can you help me please?

**Comment by jleni** [comment]
This does not seem related to a Ledger issue. Instead, as you can see in the screenshot... there is some previous error about missing WASM support

![image](https://user-images.githubusercontent.com/13698520/125291269-7c135600-e321-11eb-8cc0-d0ba9b09aeaf.png)

It seems that polkadot.js is trying to use WASM and this later result in errors in other unrelated places
