### ISSUE TITLE
Transfer not allowed

### ISSUE THREAD

**Issue by MorasDigital** [Zondax/ledger-polkadot#71]
Hello, I installed your application on Ledger Nano X: "Polkadot_sec".
I successfully received several DOT, but I cannot send it. Error: Not Allowed

**Comment by jleni** [comment]
Polkadot_sec is a very technical app used by validators. 
It was not supposed to be public in the store and we don't recommend using it.

But do not worry, it is the very same very as the standard "Polkadot" app. However, there are restrictions on what you can do with it, who you can send to, etc.

But do not worry, just only need to switch to the normal polkadot app and you will be able to transfer.
