### ISSUE TITLE
'Unexpected Value' when trying to sign a transaction

### ISSUE THREAD

**Issue by ETeissonniere** [Zondax/ledger-polkadot#73]
Not sure where it is best to report this, but basically when trying to trigger a simple balance transfer from the Polka JS interface it seems like the Ledger App app replies `Unexpected Value`. Tried to debug this without much success. I believe it also happens with Kusama.

Both the Ledger (X) and Polkadot apps are up to date.

<img width="672" alt="Capture d’écran 2021-03-03 à 09 40 24" src="https://user-images.githubusercontent.com/10683430/109778579-4937b380-7c05-11eb-9d2d-99a24478f182.png">
<img width="1949" alt="Capture d’écran 2021-03-03 à 09 41 20" src="https://user-images.githubusercontent.com/10683430/109778642-5bb1ed00-7c05-11eb-892d-b699aeca4557.png">

**Comment by totalolage** [comment]
I'm having the same issue when trying to run the `setIdentity` extrinsic.

![Unknown value error](https://imgur.com/3ZLxx2G.png)

**Comment by NickitaX** [comment]
Exactly the same issue with Ledger considering everything is up-to-date.

**Comment by ftheirs** [comment]
I'll close this issue since a it's different than the original report and it will be handled here: https://github.com/Zondax/ledger-polkadot/issues/28
