### ISSUE TITLE
Ledger cannot connect to polkadot.js

### ISSUE THREAD

**Issue by Myridium** [Zondax/ledger-polkadot#75]
I cannot connect to the Ledger and access my funds.

"No compatible devices found".

The Ledger appears when on the home screen, but if I try to connect in this state, I receive the error "Access Denied". As soon as I open up the Polkadot app it disappears from the WebUSB list.

I have tried Chromium and Brave. The Ledger firmware is up to date. The Polkadot app on the Ledger is up to date. Ledger Live is not running in the background; nothing else is trying to access the Ledger.

**Comment by StreamOfMaya** [comment]
Hi Myridium,

Thank you for reaching out to us.

Unfortunately this question should rather be addressed to polkadot directly. Polkadot has a compressive support page with a list of questions and answers on a variety of topics (https://support.polkadot.network/support/home).

In case you do not find a satisfactory answer, you can email their [Support](support@polkadot.network) for further assistance.

We will close this issue if we do not hear back from you within 2 weeks.

Thanks you.

**Comment by morkeltry** [comment]
You added the udev rules?

https://github.com/LedgerHQ/udev-rules

**Comment by StreamOfMaya** [comment]
Please create a separate issue for this question. Thanks.

**Comment by Myridium** [comment]
> You added the udev rules?
> 
> https://github.com/LedgerHQ/udev-rules

Yes, I did.

I gave up on Polkadot. Not worth the time. Closing this issue.
