### ISSUE TITLE
Reduce app size.

### ISSUE THREAD

**Issue by hirschenberger** [Zondax/ledger-polkadot#76]
Hi, it would be great if I could use the Polkadot **and** Kusama app on a Ledger Nano S.

Atm the Polkadot and Kusama apps take 112 and 120 kb which is 232kb. The Ledger S has 156kb capacity.

Is it possible to perhaps tweak with compiler flags, strip stuff or optimize the apps to fit both on a Ledger Nano S. This would be great, bc. I think it a common app combination users want to have on their Ledgers.

I looked in the code and saw that the rust-app gets built with debuginfo (maybe stripped later i.d.k.). Or twiddling with the panikhandler to save some bytes. Use the `z` optimisation instead of `s`....

**Comment by jleni** [comment]
We are aware and working on several improvements at this moment.

Nevertheless, to clarify, most of the Rust code you are referring to is not currently deployed in the apps. These are future features that are currently disabled in production.

A large amount of space is consumed in strings (pallet, methods, argument names) and support for multiple runtimes. We are looking at unifying code, etc. We already have made a lot of progress and will have some news in the near future.

**Comment by hirschenberger** [comment]
Great to hear.  I'm looking forward to new releases :+1:

**Comment by hirschenberger** [comment]
Will the lightapps be available in the ledger-live-desktop app?
