### ISSUE TITLE
Documentation: explain wth 'Light' and 'XL' refer to

### ISSUE THREAD

**Issue by morkeltry** [Zondax/ledger-polkadot#90]
In [this repo](https://github.com/Zondax/ledger-polkadot), most of the pallet features seem only to be implemented in the 'XL' column and not the 'Light' column.
It's not clear what  'light' and 'XL' are - does this mean Nano S runs only 'light'?
If so, it could be useful to state that in the README.

**Comment by jleni** [comment]
Ledger publishes two versions of the app in their app store. 
You will see a Polkadot XL version in Ledger Live when you try to install the app.
I hope this clarifies the situation.
