### ISSUE TITLE
Support `crowdloans` pallet

### ISSUE THREAD

**Issue by morkeltry** [Zondax/ledger-polkadot#91]
...on Nano S plz!

**Comment by DanielHirsbrunner** [comment]
Hello together
I assume the signing of the transaction is not the problem, just how to display it on the ledger?
Is there any timeline for the extrinsics support out of the crowdloan module?
Or is there any workaround that I could create the transaction and let it sign in the ledger?
I would like to avoid working with a hotwallet for the crowdloans...
Thank you for the update.
Daniel

**Comment by albertov19** [comment]
Hi everyone, any updates on this?

As Polkadot Crowldoans are probably close, it would be nice to have this feature in the Polkadot App of Ledger devices. This was definitely missed in the Kusama Crowdloans!

Thanks in advance

**Comment by Bird-NZ** [comment]
Hugely disappointing that Ledger & Polkadot failed to work together in time to enable crownloans via the security of Ledger. Come on people physical security is so important in this blockchain world.

**Comment by Lohann** [comment]
+1

**Comment by Hackgay** [comment]
+2

**Comment by watchzerg** [comment]
+3

**Comment by juanmanusg** [comment]
+1

**Comment by athlona64** [comment]
+1

**Comment by ftheirs** [comment]
Latest release supports crowdloans!
https://github.com/Zondax/ledger-polkadot/releases/tag/v12.9200.1
