### ISSUE TITLE
Missing Polkadot XL app in ledger-live

### ISSUE THREAD

**Issue by hirschenberger** [Zondax/ledger-polkadot#96]
I can't find a PolkadotXL App in ledger live, although there is a KusamaXL App. I need it to remove a democracy lock.

**Comment by jleni** [comment]
this depends on Ledger Live's release schedule.
We have provided both versions. I will check with them why this is not available yet.

**Comment by hirschenberger** [comment]
> this depends on Ledger Live's release schedule.
> We have provided both versions. I will check with them why this is not available yet.

Hi, I checked and PolkadotXL is still not available. @jleni Do you have any information on that? I have to get rid of that nasty democracy lock asap.

**Comment by hirschenberger** [comment]
Kind reminder, anything new @jleni ?

**Comment by hirschenberger** [comment]
Installing the experimental version works for me:

https://matrix.to/#/!FdCojkeGzZLSEoiecf:web3.foundation/$z5F4hgmOCqcY2l6HIVdoWdrART20DXEyn39Uo_ZOYAk?via=matrix.parity.io&via=matrix.org&via=corepaper.org

**Comment by jleni** [comment]
I will remind Ledger that they need to release also the XL version

**Comment by ainhoa-a** [comment]
Polkadot XL has already been released.
