### ISSUE TITLE
(Cannot find via ledger) KSM SS68 Equiv address for DOT address on Ledger

### ISSUE THREAD

**Issue by mutiks7** [Zondax/ledger-polkadot#97]
Hello,

I am using ledger HW wallet with the Polkadot browser extension.

I sent funds to the KSM SS58 Equiv address for my DOT address on Ledger. The issue is that i don't know how to add this address via ledger to the extension, so i cannot access the funds in this address. 
The account type/address index for the DOT address is 0/0 but this is not the case for the KSM equivalent. Is there a way to populate it? Or perhaps a way to see/add any ledger address that the balance is > 0?

Any help is greatly appreciated,
mutiks

**Comment by ftheirs** [comment]
url was updated! New link here: https://zondax.ch/blog/dot-recovery-mode
Please @mutiks7, let us know if this was solved or you still have problems 😄

**Comment by mutiks7** [comment]
Yes, this has been resolved!
-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



May 5, 2022, 02:06 by ***@***.***:
