### ISSUE TITLE
KSM Sent on a Karura Dot based ledger adress ; Uncapable to switch blockchain on .js

### ISSUE THREAD

**Issue by KiNDReK** [Zondax/ledger-polkadot#99]
Hey there ! 

Messed up a bit here, so long story short,

I bridged my KSM to Karura and had the great idea to choose my ledger wallet for receipient adress, which, as said above, is setup as a Polkadot wallet. And i can't switch to "allow on all blockchains" on polkadot.js, i can only rename or forget the account.

A few extra info: 
- I can see the KSM on Karura, but i'm facing an error ("Something went wrong with the query rendering of this component. Unable to find sopported chain for 0x...) every time i want to interact with the platform 

- I can't see the Ledger account when i connect on substrate/Karura and go on my account page..

- I can see all KSM on sub.id, which are on the Karura adress linked to the Ledger DOT adress "only"

So to resume, I can see the funds, but i can't switch chain to be able to use them...

Thanks !

**Comment by jleni** [comment]
As we explained privately, we need to release a Karura app and some "special mode" for this to be recoverable with a Ledger device.
This is the way you could recover the tokens that you sent incorrectly to another chain.
We will "very likely" have news about this in the following weeks ;)

**Comment by KiNDReK** [comment]
Hey !
Thanks so much for coming back to me :)
Yeah I thought that would have been the case.. looking forward to hear back from you guys ! Any idea how I could follow the launch of the app ?
Cheers ✌️

**Comment by ftheirs** [comment]
Hi @KiNDReK, [Karura repo](https://github.com/Zondax/ledger-karura) is public now! 
If you have a nanoS, you can use the installer script to install the app, and follow [these steps](https://zondax.ch/blog/recover-blocked-ksm) to recover your coins! If you have a nanoX you will have to wait until official ledger release is published.
